name: Check if the format of the dataset is correct

on:
  push:
    paths:
      - 'datasets/**'
  pull_request:
    paths:
      - 'datasets/**'

jobs:
  check_datasets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Run script
      run: bash .github/scripts/check_datasets.bash

