name: Check Datasets

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: bash ./.github/scripts/check_datasets.bash

