name: Check Dataset Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - update_datasets

jobs:
  check_datasets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Run script
      run: bash .github/scripts/check_datasets.bash
