name: Check Datasets

on: [push, pull_request]

jobs:
  "Check Datasets":
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Run script
      run: bash ./.github/scripts/check_datasets.bash

