name: Revert Commit

on:
  workflow_run:
    workflows: ["Check Directory Changes"]
    types:
      - completed

jobs:
  revert:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Check if last commit was a revert
      run: |
        if git log -1 --pretty="%an" | grep -q "GitHub Actions"; then
          echo "Last commit was made by GitHub Actions. Skipping revert..."
          exit 0
        fi

    - name: Revert last commit
      run: |
        git revert HEAD --no-edit
        git push origin main
